type Usuario @table {
  nombre: String!
  correo: String!
  rol: String!
  fechaRegistro: Timestamp!
}

type Cliente @table {
  nombre: String!
  correo: String!
  telefono: String!
  empresa: String!
  fechaRegistro: Timestamp!
  estado: String!
  etapaCrm: String!
}

type Interaccion @table {
  cliente: Cliente!
  usuario: Usuario!
  tipo: String!
  descripcion: String!
  fecha: Timestamp!
}